version: '3'
services:
  meli-mysql:
    container_name: meli-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=meli
    restart: always
    ports:
      - "3305:3306"
    volumes:
      - meli-data:/var/lib/mysql
    networks:
      - meli-backend
    command: --default-authentication-plugin=mysql_native_password

  meli-web:
    container_name: meli-web
    build: .
    restart: always
    ports:
      - "8000:4000"
    depends_on:
      - meli-mysql
    volumes:
      - ".:/app"
    links:
      - "meli-mysql:meli-mysql-db"
    networks:
      - meli-backend
networks:
  meli-backend:

volumes:
  meli-data:
